version: '3.10'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  snake:
    build: .
    container_name: snake
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb+srv://deniz:denizpjatk@cluster0.5y1k84l.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
