name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
        working-directory: s28330-SnakeGame/Game

      - name: Run tests
        run: |
          pytest test_snake_game.py
        working-directory: s28330-SnakeGame/Game

      - name: Build Docker image
        run: docker build -t snakegame:latest .
        working-directory: s28330-SnakeGame/Game