name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Install dependencies
        run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
          pytest snake_game/test_snake_game.py
        working-directory: Game

      - name: Run tests
        run: |
           pytest snake_game/test_snake_game.py
        working-directory: Game

      - name: Build Docker image
        run: docker build -t game-snake:latest .
        working-directory: Game